# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc810e88901d2167776c9c5f714ac576aa5844d1b73469fe0efe6cd901f9019e21dd9bee1904a5f7dd61b87e3458c2423b1e838bc90a012170dcc2b27916c714

test:
  secret_key_base: c77a04a122b9d9b546188e60eabf8d488017432170bd4c23c6a2b772100a5d2a8a4f150f97d099394f22016adf58ce750e5e3ef9b9a3616d875e1e7c8b6e2e9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
